---
title: "Heatmaps"
subtitle: "2022 Season"
format:
  html:
      theme: cosmo
      self-contained: true
      toc: true
editor: visual
author: James Brown
---

```{r}
#| label: load-packages-and-data
#| include: false
#| message: false

# Libraries and Data
library(tidyverse)
library(ztable)
library(ggthemes)
library(paletteer)
combined_stats_table <- read_rds("../../Data/RDS-files/combined_stats_table_2022.rds")

# Options
options(ztable.type="html")
options(ztable.colnames.bold=TRUE)
```

```{r}
#| label: cba-heatmap-function
#| include: false
#| message: false

create_cba_heatmap <- function(team_name){
heatmap_df_cbas <-
combined_stats_table %>%
  filter(team == team_name) %>%
  select(player_name, round_number, CBA_percentage) %>%
  group_by(player_name) %>%
  filter(max(CBA_percentage, na.rm = TRUE) > 0) %>%
  mutate(mean_CBA_percentage = mean(CBA_percentage, na.rm = TRUE)) %>%
  arrange(desc(mean_CBA_percentage), player_name)

heatmap_plot <-
ggplot(heatmap_df_cbas, aes(round_number, reorder(player_name, mean_CBA_percentage), fill = CBA_percentage)) +
  geom_tile() +
  scale_x_discrete(guide = guide_axis(angle=90)) +
  xlab("Round") + 
  ylab("Player") +
  labs(fill = "CBA %") +
  scale_fill_paletteer_c(`"viridis::plasma"`) +
  theme_tufte(ticks = FALSE) +
  geom_vline(xintercept = seq(0.5,16.5, by = 1), colour = "grey50") +
  geom_hline(yintercept = seq(0.5, length(unique(heatmap_df_cbas$player_name)) + 0.5, by = 1), colour = "grey50") +
  theme(panel.background = element_rect(fill = "darkblue",colour = "white")) +
  geom_vline(xintercept = seq(16.52, 16.55, by = 0.01), colour = "white") +
  geom_vline(xintercept = seq(0.40, 0.48, by = 0.01), colour = "white") +
  geom_hline(yintercept = seq(length(unique(heatmap_df_cbas$player_name)) + 0.55, length(unique(heatmap_df_cbas$player_name)) + 1.5, by = 0.01), colour = "white") +
  geom_hline(yintercept = seq(0.4, 0.45, by = 0.01), colour = "white") +
  geom_text(mapping = aes(label = round(CBA_percentage, 1)), size = 3,
            colour = case_when(heatmap_df_cbas$CBA_percentage > 60 ~ "black", heatmap_df_cbas$CBA_percentage <= 60 ~ "white"), fontface = "bold")

print(heatmap_plot)
}

```

## Centre Bounce Attendances

::: panel-tabset
## Adelaide Crows

```{r}
#| echo: false
create_cba_heatmap("Adelaide Crows")
```

## Brisbane Lions
```{r}
#| echo: false
create_cba_heatmap("Brisbane Lions")
```

:::