---
title: "Draft and FA Report"
subtitle: "2022 Season"
format:
  html:
      df-print: kable
      theme: cosmo
      self-contained: true
      toc: true
editor: visual
---

```{r}
#| label: load-packages-and-data
#| include: false
#| echo: false

library(tidyverse)
`%notin%` <- Negate(`%in%`)

draft_recap <- read_csv("../../../../Data/CSV-files/draft_recap_2022.csv")
combined_stats_table <- read_rds("../../../../Data/RDS-files/combined_stats_table_2022.rds")
```

```{r}
#| label: data-setup
#| include: false
#| echo: false


top_defenders <-
  combined_stats_table %>%
  filter(fantasy_defender_status) %>%
  filter(!fantasy_forward_status) %>%
  filter(TOG > 50) %>%
  filter(games_played >= 5) %>%
  group_by(player_name) %>%
  summarise(avg_score = mean(fantasy_points, na.rm = TRUE), games_played = max(games_played)) %>%
  arrange(desc(avg_score)) %>%
  head(48) %>%
  ungroup() %>%
  mutate(mean_position_score = mean(avg_score),
         z_score = scale(avg_score)[,1]) %>%
  mutate(across(where(is.numeric), ~round(., 2)))

top_midfielders <-
  combined_stats_table %>%
  filter(fantasy_midfield_status) %>%
  filter(!fantasy_forward_status) %>%
  filter(!fantasy_defender_status) %>%
  filter(!fantasy_ruck_status) %>%
  filter(TOG > 50) %>%
  filter(games_played >= 5) %>%
  group_by(player_name) %>%
  summarise(avg_score = mean(fantasy_points, na.rm = TRUE), games_played = max(games_played)) %>%
  arrange(desc(avg_score)) %>%
  head(64) %>%
  ungroup() %>%
  mutate(mean_position_score = mean(avg_score),
         z_score = scale(avg_score)[,1]) %>%
  mutate(across(where(is.numeric), ~round(., 2)))

top_rucks <-
  combined_stats_table %>%
  filter(fantasy_ruck_status) %>%
  filter(!fantasy_forward_status) %>%
  filter(!fantasy_defender_status) %>%
  filter(TOG > 50) %>%
  filter(games_played >= 5) %>%
  group_by(player_name) %>%
  summarise(avg_score = mean(fantasy_points, na.rm = TRUE), games_played = max(games_played)) %>%
  arrange(desc(avg_score)) %>%
  head(16) %>%
  ungroup() %>%
  mutate(mean_position_score = mean(avg_score),
         z_score = scale(avg_score)[,1]) %>%
  mutate(across(where(is.numeric), ~round(., 2)))

top_forwards <-
  combined_stats_table %>%
  filter(fantasy_forward_status) %>%
  filter(TOG > 50) %>%
  filter(games_played >= 5) %>%
  group_by(player_name) %>%
  summarise(avg_score = mean(fantasy_points, na.rm = TRUE), games_played = max(games_played)) %>%
  arrange(desc(avg_score)) %>%
  head(48) %>%
  ungroup() %>%
  mutate(mean_position_score = mean(avg_score),
         z_score = scale(avg_score)[,1]) %>%
  mutate(across(where(is.numeric), ~round(., 2)))

all_player_rankings <-
  bind_rows(top_defenders, top_midfielders, top_rucks, top_forwards) %>%
  group_by(player_name) %>%
  filter(z_score == max(z_score)) %>%
  ungroup() %>%
  arrange(desc(z_score)) %>%
  mutate(ranking = row_number()) %>%
  relocate(ranking, .after = player_name) %>%
  mutate(across(where(is.numeric), ~round(., 2)))
```

```{r}
#| echo: false
#| include: false

best_draft_picks <-
  all_player_rankings %>%
  left_join(draft_recap) %>%
  filter(!is.na(pick)) %>%
  mutate(difference = pick - ranking) %>%
  arrange(desc(difference))

best_FA_pickups <-
  all_player_rankings %>%
  filter(player_name %notin% draft_recap$player_name)

```

```{r}
#| echo: false
#| include: false

worst_draft_picks <-
combined_stats_table %>%
  filter(player_name %in% draft_recap$player_name)

# Defender
top_defenders_worst <-
  worst_draft_picks %>%
  filter(fantasy_defender_status) %>%
  filter(!fantasy_forward_status) %>%
  filter(TOG > 50) %>%
  group_by(player_name) %>%
  summarise(avg_score = mean(fantasy_points, na.rm = TRUE), games_played = max(games_played)) %>%
  arrange(desc(avg_score)) %>%
  ungroup() %>%
  mutate(mean_position_score = mean(avg_score),
         z_score = scale(avg_score)[,1])

# Midfield
top_midfielders_worst <-
  worst_draft_picks %>%
  filter(fantasy_midfield_status) %>%
  filter(!fantasy_forward_status) %>%
  filter(!fantasy_defender_status) %>%
  filter(!fantasy_ruck_status) %>%
  filter(TOG > 50) %>%
  group_by(player_name) %>%
  summarise(avg_score = mean(fantasy_points, na.rm = TRUE), games_played = max(games_played)) %>%
  arrange(desc(avg_score)) %>%
  ungroup() %>%
  mutate(mean_position_score = mean(avg_score),
         z_score = scale(avg_score)[,1])
# Ruck
top_rucks_worst <-
  worst_draft_picks %>%
  filter(fantasy_ruck_status) %>%
  filter(!fantasy_forward_status) %>%
  filter(!fantasy_defender_status) %>%
  filter(TOG > 50) %>%
  group_by(player_name) %>%
  summarise(avg_score = mean(fantasy_points, na.rm = TRUE), games_played = max(games_played)) %>%
  arrange(desc(avg_score)) %>%
  ungroup() %>%
  mutate(mean_position_score = mean(avg_score),
         z_score = scale(avg_score)[,1])

# Forward
top_forwards_worst <-
  worst_draft_picks %>%
  filter(fantasy_forward_status) %>%
  filter(TOG > 50) %>%
  group_by(player_name) %>%
  summarise(avg_score = mean(fantasy_points, na.rm = TRUE), games_played = max(games_played)) %>%
  arrange(desc(avg_score)) %>%
  ungroup() %>%
  mutate(mean_position_score = mean(avg_score),
         z_score = scale(avg_score)[,1])

# Combine into 1 to get redraft ranking
all_player_rankings_worst <-
  bind_rows(top_defenders_worst, top_midfielders_worst, top_rucks_worst, top_forwards_worst) %>%
  group_by(player_name) %>%
  filter(z_score == max(z_score)) %>%
  ungroup() %>%
  arrange(desc(z_score)) %>%
  mutate(ranking = row_number())

# Get actual draft position
worst_draft_picks <-
  all_player_rankings_worst %>%
  left_join(draft_recap) %>%
  mutate(difference = pick - ranking) %>%
  arrange(difference)

```

```{r}
#| echo: false
#| include: false

# Exclude bye rounds
bye_rounds <- c("Round 12", "Round 13", "Round 14")

combined_stats_table_no_byes <-
combined_stats_table %>%
  filter(round_number %notin% bye_rounds)

# Get total games missed
games_missed <-
  combined_stats_table_no_byes %>%
  group_by(player_name) %>%
  summarise(games_played = max(row_number())) %>%
  mutate(games_missed = 13 - games_played)

# Get Draft picks and positions
draft_picks_games_missed <-
games_missed %>%
  left_join(draft_recap) %>%
  filter(!is.na(pick)) %>%
  arrange(pick)

# Get total games missed by top draft picks from first 15 rounds
first_15_player_games_missed <-
draft_picks_games_missed %>%
  filter(pick <= 80) %>%
  group_by(team) %>%
  summarise(player_games_missed = sum(games_missed), player_games_played = sum(games_played)) %>%
  mutate(max_games_played = player_games_missed + player_games_played,
         percentage_games_from_picks = round(100*(player_games_played / max_games_played), digits = 2)) %>%
  arrange(percentage_games_from_picks)

```

```{r}
#| echo: false
#| include: false

# Create draft round variable
rounds <-
  c(
    rep(1, 8),
    rep(2, 8),
    rep(3, 8),
    rep(4, 8),
    rep(5, 8),
    rep(6, 8),
    rep(7, 8),
    rep(8, 8),
    rep(9, 8),
    rep(10, 8),
    rep(11, 8),
    rep(12, 8),
    rep(13, 8),
    rep(14, 8),
    rep(15, 8),
    rep(16, 8),
    rep(17, 8),
    rep(18, 8),
    rep(19, 8),
    rep(20, 8),
    rep(21, 8),
    rep(22, 8)
  )

draft_recap <-
  draft_recap %>%
  mutate(round = rounds)

# Get best draft pick by round
best_pick_by_round <-
  draft_recap %>%
  left_join(all_player_rankings %>% select(player_name, ranking)) %>%
  group_by(round) %>%
  filter(ranking == min(ranking, na.rm = TRUE))

# Get worst draft pick by round
worst_pick_by_round <-
  draft_recap %>%
  left_join(all_player_rankings_worst %>% select(player_name, ranking)) %>%
  group_by(round) %>%
  filter(ranking == max(ranking, na.rm = TRUE))

```

## 20 Best Draft Picks

```{r}
#| echo: false

best_draft_picks %>%
  select(
    Player = player_name,
    Team = team,
    Avg = avg_score,
    `Z-Score` = z_score,
    Games = games_played,
    Pick = pick,
    Rank = ranking,
    Diff = difference
  ) %>%
  head(20)

```

## Best Draft Picks By Round

```{r}
#| echo: false

best_pick_by_round %>%
  select(
    Round = round,
    Player = player_name,
    Team = team,
    Pick = pick,
    Rank = ranking
  )

```

## 20 Best FA Pickups

```{r}
#| echo: false

best_FA_pickups %>%
  select(
    Player = player_name,
    Avg = avg_score,
    `Z-Score` = z_score,
    Games = games_played,
    Rank = ranking
  ) %>%
  head(20)

```

## 20 Worst Draft Picks

```{r}
#| echo: false

worst_draft_picks %>%
  select(
    Player = player_name,
    Team = team,
    Avg = avg_score,
    `Z-Score` = z_score,
    Games = games_played,
    Pick = pick,
    Rank = ranking,
    Diff = difference
  ) %>%
  head(20)

```

## Worst Draft Picks By Round

```{r}
#| echo: false

worst_pick_by_round %>%
  select(
    Round = round,
    Player = player_name,
    Team = team,
    Pick = pick,
    Rank = ranking
  )

```

## Most Games Missed

```{r}
#| echo: false

first_15_player_games_missed %>%
  select(Team = team,
         `% of Total Games Missed by First 10 Picks` = percentage_games_from_picks)
```
